version: '3'

services:
    nginx:
        image: nginx:1.16
        container_name: clirep_nginx
        ports:
            - "8000:8000"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
            - ./nginx/log:/var/log/nginx
            - ./static:/static
        depends_on:
            - python
        environment:
            TZ: 'Asia/Tokyo'

    db:
        image: mysql:5.7
        container_name: clirep_db
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DATABASE}
            MYSQL_USER: ${USERNAME}
            MYSQL_PASSWORD: ${USERPASS}
            MYSQL_ROOT_PASSWORD: ${ROOTPASS}
            TZ: 'Asia/Tokyo'
        volumes:
            - ./mysql:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
            - ./backup:/var/lib/backup

    python:
        build: ./python
        container_name: clirep_app
        command: uwsgi --socket :8000 --module clinic_reputation.wsgi 
        volumes:
            - ./src:/code
            - ./static:/static
        expose:
            - "8000"
        depends_on:
            - db
        environment:
            TZ: 'Asia/Tokyo'
