# Generated by Django 3.0.4 on 2021-03-13 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('lgbt', 'LGBT'), ('noanswer', '未回答')], max_length=10, verbose_name='性別')),
                ('address', models.CharField(max_length=4, verbose_name='住所')),
                ('carrer', models.TextField(max_length=1000, verbose_name='キャリア')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
