# Generated by Django 3.0.4 on 2021-01-13 07:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255, verbose_name='治療院名')),
                ('directer_name', models.CharField(max_length=255, verbose_name='代表者')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('phone_num', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('holiday', models.CharField(max_length=255, verbose_name='休日')),
                ('treatment', models.TextField(max_length=1000, verbose_name='施術内容')),
                ('homepage', models.CharField(max_length=255, verbose_name='HP')),
                ('station', models.CharField(max_length=255, verbose_name='最寄り駅')),
            ],
            options={
                'verbose_name_plural': '治療院情報',
            },
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(1, '男性'), (2, '女性'), (3, 'LGBT'), (4, '未回答')], max_length=10, verbose_name='性別')),
                ('age', models.PositiveIntegerField(choices=[(20, '20代'), (30, '30代'), (40, '40代'), (50, '50代'), (60, '60代以上')], verbose_name='年齢')),
                ('condition', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='待遇面')),
                ('staff', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='スタッフ間の仲の良さ')),
                ('ventilation', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='風通しの良さ')),
                ('respect', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='スタッフ同士の相互尊重')),
                ('growth', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='成長環境')),
                ('management', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='経営状況')),
                ('evaluation', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='人事評価の適正さ')),
                ('compliance', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='法令遵守')),
                ('reason', models.TextField(max_length=1000, verbose_name='入社理由・ギャップ')),
                ('culture', models.TextField(max_length=1000, verbose_name='組織文化')),
                ('reward_growth', models.TextField(max_length=1000, verbose_name='働きがいや成長環境')),
                ('supply', models.TextField(max_length=1000, verbose_name='給与制度')),
                ('women_work', models.TextField(max_length=1000, verbose_name='女性の働きやすさ')),
                ('worklife', models.TextField(max_length=1000, verbose_name='ワークライフバランス')),
                ('strength_weak', models.TextField(max_length=1000, verbose_name='治療院の強みや弱み')),
                ('director', models.TextField(max_length=1000, verbose_name='治療院の代表者')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.Clinic')),
            ],
            options={
                'verbose_name_plural': '評価情報',
            },
        ),
    ]
