# Generated by Django 3.0.4 on 2021-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('lgbt', 'LGBT'), ('noanswer', '未回答')], max_length=10, verbose_name='性別'),
        ),
    ]
