# Generated by Django 3.0.4 on 2021-01-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputation',
            name='age',
            field=models.PositiveIntegerField(choices=[(20, '20代'), (30, '30代'), (40, '40代'), (50, '50代'), (60, '60代以上')], default=20, verbose_name='年齢'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reputation',
            name='gender',
            field=models.CharField(choices=[(1, '男性'), (2, '女性'), (3, 'LGBT'), (4, '未回答')], default=1, max_length=10, verbose_name='性別'),
            preserve_default=False,
        ),
    ]
